# Run webhook deploy when chart installed
apiVersion: batch/v1
kind: Job
metadata:
  name: rancher-flat-network-webhook-deploy
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        app: rancher-flat-network-webhook-deploy
    spec:
      serviceAccountName: multus
      restartPolicy: OnFailure
      containers:
      - image: {{ template "system_default_registry" . }}{{ .Values.webhookDeploy.image.repository }}:{{ .Values.webhookDeploy.image.tag }}
        name: rancher-flat-network-webhook-deploy
        imagePullPolicy: {{ .Values.webhookDeploy.image.pullPolicy }}

---
# Run webhook deploy every month to renew certificate.
apiVersion: batch/v1
kind: CronJob
metadata:
  name: rancher-flat-network-webhook-deploy
  namespace: kube-system
spec:
  schedule: "{{ .Values.webhookDeploy.rolloutSchedule }}"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: rancher-flat-network-webhook-deploy
        spec:
          serviceAccountName: multus
          restartPolicy: OnFailure
          containers:
          - image: {{ template "system_default_registry" . }}{{ .Values.webhookDeploy.image.repository }}:{{ .Values.webhookDeploy.image.tag }}
            name: rancher-flat-network-webhook-deploy
            imagePullPolicy: {{ .Values.webhookDeploy.image.pullPolicy }}
            env:
            - name: ROLLOUT_FLATNETWORK_DEPLOYMENT
              value: "true"
