apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: example-daemonset
  namespace: default
  labels:
    app: example-archlinux-daemontest
spec:
  selector:
    matchLabels:
      app: example-archlinux-daemontest
  template:
    metadata:
      labels:
        app: example-archlinux-daemontest
      annotations:
        flatnetwork.pandaria.io/ip: "auto"
        flatnetwork.pandaria.io/subnet: "example-macvlan-subnet"
        flatnetwork.pandaria.io/mac: ""
        k8s.v1.cni.cncf.io/networks: '[{"name":"rancher-flat-network","interface":"eth1"}]'
    spec:
      containers:
      - name: example-archlinux-daemontest
        image: harborlocal.hxstarrys.me/library/archlinux-net-test:latest
        imagePullPolicy: Always

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: example-daemonset-ipv6
  namespace: default
  labels:
    app: example-archlinux-daemontest-ipv6
spec:
  selector:
    matchLabels:
      app: example-archlinux-daemontest-ipv6
  template:
    metadata:
      labels:
        app: example-archlinux-daemontest-ipv6
      annotations:
        flatnetwork.pandaria.io/ip: "auto"
        flatnetwork.pandaria.io/subnet: "example-macvlan-subnet-ipv6"
        flatnetwork.pandaria.io/mac: ""
        k8s.v1.cni.cncf.io/networks: '[{"name":"rancher-flat-network","interface":"eth1"}]'
    spec:
      containers:
      - name: example-archlinux-daemontest-ipv6
        image: harborlocal.hxstarrys.me/library/archlinux-net-test:latest
        imagePullPolicy: Always
