apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: alpine-macvlan-daemonset
  namespace: default
  labels:
    app: alpine-macvlan-daemonset
spec:
  selector:
    matchLabels:
      app: alpine-macvlan-daemonset
  template:
    metadata:
      labels:
        app: alpine-macvlan-daemonset
      annotations:
        flatnetwork.pandaria.io/ip: "auto"
        flatnetwork.pandaria.io/subnet: "macvlan-subnet100"
        flatnetwork.pandaria.io/mac: ""
        k8s.v1.cni.cncf.io/networks: '[{"name":"rancher-flat-network","interface":"eth1"}]'
        # v1.multus-cni.io/default-network: '[{"name":"rancher-flat-network","interface":"eth0"}]'
    spec:
      containers:
      - name: alpine-macvlan-daemonset
        image: alpine
        imagePullPolicy: Always
        command: ["sleep"]
        args: ["infinity"]

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: alpine-macvlan-daemonset-ipv6
  namespace: default
  labels:
    app: alpine-macvlan-daemonset-ipv6
spec:
  selector:
    matchLabels:
      app: alpine-macvlan-daemonset-ipv6
  template:
    metadata:
      labels:
        app: alpine-macvlan-daemonset-ipv6
      annotations:
        flatnetwork.pandaria.io/ip: "auto"
        flatnetwork.pandaria.io/subnet: "macvlan-ipv6-subnet101"
        flatnetwork.pandaria.io/mac: ""
        k8s.v1.cni.cncf.io/networks: '[{"name":"rancher-flat-network","interface":"eth1"}]'
    spec:
      containers:
      - name: alpine-macvlan-daemonset-ipv6
        image: alpine
        imagePullPolicy: Always
        command: ["sleep"]
        args: ["infinity"]
