apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment
  namespace: default
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        flatnetwork.pandaria.io/ip: "auto"
        flatnetwork.pandaria.io/subnet: "example-macvlan-subnet"
        flatnetwork.pandaria.io/mac: ""
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-alpine
  namespace: default
  labels:
    app: alpine
spec:
  replicas: 3
  selector:
    matchLabels:
      app: alpine
  template:
    metadata:
      labels:
        app: alpine
      annotations:
        flatnetwork.pandaria.io/ip: "auto"
        flatnetwork.pandaria.io/subnet: "example-macvlan-subnet"
        flatnetwork.pandaria.io/mac: ""
    spec:
      containers:
      - name: alpine
        image: alpine
        command:
        - "sleep"
        args:
        - "infinity"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-alpine-ipv6
  namespace: default
  labels:
    app: alpine-ipv6
spec:
  replicas: 3
  selector:
    matchLabels:
      app: alpine-ipv6
  template:
    metadata:
      labels:
        app: alpine-ipv6
      annotations:
        flatnetwork.pandaria.io/ip: "auto"
        flatnetwork.pandaria.io/subnet: "example-macvlan-subnet-ipv6"
        flatnetwork.pandaria.io/mac: ""
    spec:
      containers:
      - name: alpine
        image: alpine
        command:
        - "sleep"
        args:
        - "infinity"
