apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-macvlan-deployment
  namespace: default
  labels:
    app: alpine
spec:
  replicas: 3
  selector:
    matchLabels:
      app: alpine
  template:
    metadata:
      labels:
        app: alpine
      annotations:
        flatnetwork.pandaria.io/ip: "auto"
        flatnetwork.pandaria.io/subnet: "macvlan-subnet100"
        flatnetwork.pandaria.io/mac: ""
        k8s.v1.cni.cncf.io/networks: '[{"name":"rancher-flat-network","interface":"eth1"}]'
    spec:
      containers:
      - name: alpine
        image: alpine
        command: ["sleep"]
        args: ["infinity"]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-macvlan-deployment-ipv6
  namespace: default
  labels:
    app: alpine-ipv6
spec:
  replicas: 3
  selector:
    matchLabels:
      app: alpine-ipv6
  template:
    metadata:
      labels:
        app: alpine-ipv6
      annotations:
        flatnetwork.pandaria.io/ip: "auto"
        flatnetwork.pandaria.io/subnet: "macvlan-ipv6-subnet101"
        flatnetwork.pandaria.io/mac: ""
        k8s.v1.cni.cncf.io/networks: '[{"name":"rancher-flat-network","interface":"eth1"}]'
    spec:
      containers:
      - name: alpine-ipv6
        image: alpine
        command: ["sleep"]
        args: ["infinity"]
