kind: Pod
apiVersion: v1
metadata:
  name: example-macvlan-pod
  namespace: "default"
  annotations:
    flatnetwork.pandaria.io/ip: "auto"
    flatnetwork.pandaria.io/subnet: "example-macvlan-subnet"
    flatnetwork.pandaria.io/mac: ""
    k8s.v1.cni.cncf.io/networks: '[{"name":"rancher-flat-network","interface":"eth1"}]'
spec:
  nodeName: k3s-master-1
  containers:
  - name: archlinux-net-test
    image: harborlocal.hxstarrys.me/library/archlinux-net-test:latest
