kind: Pod
apiVersion: v1
metadata:
  name: example-macvlan-pod
  namespace: "default"
  annotations:
    flatnetwork.pandaria.io/ip: "auto"
    flatnetwork.pandaria.io/subnet: "example-macvlan-subnet"
    flatnetwork.pandaria.io/mac: ""
spec:
  containers:
  - name: nginx
    image: nginx
