---
# Run webhook deploy every month to renew certificate.
apiVersion: batch/v1
kind: CronJob
metadata:
  name: flatnetwork-webhook-deploy
  namespace: kube-system
spec:
  schedule: "{{ .Values.webhookDeploy.rolloutSchedule }}"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: flatnetwork-webhook-deploy
        spec:
          serviceAccountName: multus
          restartPolicy: OnFailure
          containers:
          - image: {{ template "system_default_registry" . }}{{ .Values.webhookDeploy.image.repository }}:{{ .Values.webhookDeploy.image.tag }}
            name: flatnetwork-webhook-deploy
            imagePullPolicy: {{ .Values.webhookDeploy.image.pullPolicy }}
            env:
            - name: ROLLOUT_FLATNETWORK_DEPLOYMENT
              value: "true"

---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: flatnetwork-webhook-certs
  namespace: kube-system
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNUakNDQWZTZ0F3SUJBZ0lJTFZqRkh3RXMxZkl3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxYTmxjblpsY2kxallVQXhOekU0T0RVNU56STJNQjRYRFRJME1EWXlNREExTURJd05sb1hEVEkxTURZeQpNREExTURJd05sb3dIREVNTUFvR0ExVUVDaE1EYXpOek1Rd3dDZ1lEVlFRREV3TnJNM013V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFTY0dxODhlSTZKQ0xxODdQYysyLzZYRHhxVHM3VmlzRG9EZm4wRGtHS2UKYjVVWXYyYmRFR1crdHpwSkpxbmhqRC9iRDVPbWMrNGh1OFR6Rmx4bUFTaitvNElCRnpDQ0FSTXdEZ1lEVlIwUApBUUgvQkFRREFnV2dNQk1HQTFVZEpRUU1NQW9HQ0NzR0FRVUZCd01CTUI4R0ExVWRJd1FZTUJhQUZNakxFYVp5CmhkMXlud2NVS2pKQVZ6SEFSeUdETUlIS0JnTlZIUkVFZ2NJd2diK0NGR3N6WkMxbGVHRnRjR3hsTFhObGNuWmwKY2kwd2doUnJNMlF0WlhoaGJYQnNaUzF6WlhKMlpYSnNZb0lLYTNWaVpYSnVaWFJsYzRJU2EzVmlaWEp1WlhSbApjeTVrWldaaGRXeDBnaFpyZFdKbGNtNWxkR1Z6TG1SbFptRjFiSFF1YzNaamdpUnJkV0psY201bGRHVnpMbVJsClptRjFiSFF1YzNaakxtTnNkWE4wWlhJdWJHOWpZV3lDQ1d4dlkyRnNhRzl6ZEljRUFBQUFBSWNFQ2lzQUFZY0UKZndBQUFZY0VyQklBQTRjUUFBQUFBQUFBQUFBQUFBQUFBQUFBQVRBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlFQQo3MkgvQ0QwTWdRNFVscGJmMitoZ205MktiOUFXSTZwdnZta1NIVXR4YS8wQ0lEVnlIbXRNU1FaSXZraTBEVVhDCjI2WFNRUzF4bXlGZks0VWE1cmZLdzBORAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCZHpDQ0FSMmdBd0lCQWdJQkFEQUtCZ2dxaGtqT1BRUURBakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5CmRtVnlMV05oUURFM01UZzROVGszTWpZd0hoY05NalF3TmpJd01EVXdNakEyV2hjTk16UXdOakU0TURVd01qQTIKV2pBak1TRXdId1lEVlFRRERCaHJNM010YzJWeWRtVnlMV05oUURFM01UZzROVGszTWpZd1dUQVRCZ2NxaGtqTwpQUUlCQmdncWhrak9QUU1CQndOQ0FBUlZ4ajBtQ2wxSlZsSDdud2J1aUV4dlFTVnRSclZEMW1ZazZsMlpMaEgwClR6cE9wY2JPWGNnc3BnT2hsVThBajdvNVFQK3pNTHZBUUtSY2NIeFprK0o0bzBJd1FEQU9CZ05WSFE4QkFmOEUKQkFNQ0FxUXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVV5TXNScG5LRjNYS2ZCeFFxTWtCWApNY0JISVlNd0NnWUlLb1pJemowRUF3SURTQUF3UlFJZ05kMVNQYzhYWmV2d1Z6V29QazVwUCtCVng4U3ZESTlJCkpPcWNrVmxtRkFnQ0lRQzZOd05lMmxOVGFnTXJxM24xU1M1MzU2WGIxeVk5OWFYcmdFakJ6a3hTNWc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUNLNm1rODg1b25MUHZrTkx4TXNZRlU1aXVja1MrVmlMNDdRNVFSWDFwRXpvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFbkJxdlBIaU9pUWk2dk96M1B0ditsdzhhazdPMVlyQTZBMzU5QTVCaW5tK1ZHTDltM1JCbAp2cmM2U1NhcDRZdy8ydytUcG5QdUlidkU4eFpjWmdFby9nPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
