# ---
# apiVersion: apps/v1
# kind: DaemonSet
# metadata:
#   name: flatnetwork-cni-ds
#   namespace: kube-system
#   labels:
#     name: flatnetwork-cni-ds
# spec:
#   selector:
#     matchLabels:
#       name: flatnetwork-cni-ds
#   updateStrategy:
#     type: RollingUpdate
#   template:
#     metadata:
#       labels:
#         name: flatnetwork-cni-ds
#     spec:
#       hostNetwork: true
#       tolerations:
#       - operator: Exists
#       serviceAccountName: multus
#       containers:
#       - name: flatnetwork-cni
#         image: {{ template "system_default_registry" . }}{{ .Values.staticMacvlan.image.repository }}:{{ .Values.staticMacvlan.image.tag }}
#         imagePullPolicy: {{ .Values.staticMacvlan.image.pullPolicy }}
#         command: ["/entrypoint.sh"]
#         resources:
#           requests:
#             cpu: "100m"
#             memory: "50Mi"
#           limits:
#             cpu: "100m"
#             memory: "50Mi"
#         securityContext:
#           privileged: true
#         volumeMounts:
#         - name: cni
#           mountPath: /host/etc/cni/net.d
#         - name: cnibin
#           mountPath: /host/opt/cni/bin
#       volumes:
#       - name: cni
#         hostPath:
#           path: {{ template "multus_cniconf_host_path" . }}
#       - name: cnibin
#         hostPath:
#           path: {{ template "multus_cnibin_host_path" . }}
