---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: rancher-flat-network-cni-ds
  namespace: cattle-flat-network
  labels:
    name: rancher-flat-network-cni-ds
spec:
  selector:
    matchLabels:
      name: rancher-flat-network-cni-ds
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: rancher-flat-network-cni-ds
    spec:
      hostNetwork: true
      tolerations:
      - operator: Exists
      serviceAccountName: rancher-flat-network-multus
      containers:
      - name: flat-network-cni
        image: {{ template "system_default_registry" . }}{{ .Values.flatNetworkCNI.image.repository }}:{{ .Values.flatNetworkCNI.image.tag }}
        imagePullPolicy: {{ .Values.flatNetworkCNI.image.pullPolicy }}
        command: ["/entrypoint.sh"]
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "100m"
            memory: "100Mi"
        securityContext:
          privileged: true
        volumeMounts:
        - name: cni
          mountPath: /host/etc/cni/net.d
        - name: cnibin
          mountPath: /host/opt/cni/bin
      volumes:
      - name: cni
        hostPath:
          path: {{ template "multus_cniconf_host_path" . }}
      - name: cnibin
        hostPath:
          path: {{ template "multus_cnibin_host_path" . }}
