---
# Run webhook deploy every month to renew certificate.
apiVersion: batch/v1
kind: CronJob
metadata:
  name: flatnetwork-webhook-deploy
  namespace: kube-system
spec:
  schedule: "{{ .Values.webhookDeploy.rolloutSchedule }}"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: flatnetwork-webhook-deploy
        spec:
          serviceAccountName: multus
          restartPolicy: OnFailure
          containers:
          - image: {{ template "system_default_registry" . }}{{ .Values.webhookDeploy.image.repository }}:{{ .Values.webhookDeploy.image.tag }}
            name: flatnetwork-webhook-deploy
            imagePullPolicy: {{ .Values.webhookDeploy.image.pullPolicy }}
            env:
            - name: ROLLOUT_FLATNETWORK_DEPLOYMENT
              value: "true"
