apiVersion: batch/v1
kind: Job
metadata:
  name: flatnetwork-webhook-deploy
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        app: flatnetwork-webhook-deploy
    spec:
      serviceAccountName: multus
      restartPolicy: OnFailure
      containers:
      - image: {{ template "system_default_registry" . }}{{ .Values.webhookDeploy.image.repository }}:{{ .Values.webhookDeploy.image.tag }}
        name: flatnetwork-webhook-deploy
        imagePullPolicy: {{ .Values.webhookDeploy.image.pullPolicy }}
        lifecycle:
          preStop:
            exec:
              command:
              - "/bin/bash"
              - "-c"
              - "/pre-stop-hook.sh"
