apiVersion: flatnetwork.pandaria.io/v1
kind: FlatNetworkSubnet
metadata:
  name: ipvlan-subnet200
  namespace: cattle-flat-network
spec:
  vlan: 200
  cidr: 192.168.200.0/24
  flatMode: ipvlan
  gateway: ""
  master: eth0
  mode: "l2"
  routes:
  - dev: "eth0"
    dst: "99.99.0.0/16"
    src: ""
    via: ""
    priority: 0
  - dev: "eth0"
    dst: "99.100.0.0/16"
    src: ""
    via: ""
    priority: 100
  - dev: "eth0"
    dst: "99.110.0.0/16"
    src: ""
    via: ""
    priority: 200
  routeSettings:
    addNodeCIDR: true
    addPodIPToHost: true
    flatNetworkDefaultGateway: false
  ranges:
  - from: 192.168.200.100
    to: 192.168.200.200
