apiVersion: flatnetwork.pandaria.io/v1
kind: FlatNetworkSubnet
metadata:
  name: ipvlan-ipv6-subnet201
  namespace: cattle-flat-network
spec:
  vlan: 201
  cidr: fd00:eeee::/64
  flatMode: ipvlan
  gateway: ""
  master: eth0
  mode: "l2"
  flatNetworkDefaultGateway:
    enable: false
  ranges:
  - from: fd00:eeee::1000
    to: fd00:eeee::ffff
