apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-ipvlan-deployment
  namespace: default
  labels:
    app: alpine-ipvlan
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alpine-ipvlan
  template:
    metadata:
      labels:
        app: alpine-ipvlan
      annotations:
        flatnetwork.pandaria.io/ip: "auto"
        flatnetwork.pandaria.io/subnet: "ipvlan-subnet200"
        flatnetwork.pandaria.io/mac: ""
        k8s.v1.cni.cncf.io/networks: '[{"name":"rancher-flat-network","interface":"eth1"}]'
    spec:
      containers:
      - name: alpine-ipvlan
        image: alpine
        command: ["sleep"]
        args: ["infinity"]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-ipvlan-deployment-ipv6
  namespace: default
  labels:
    app: alpine-ipvlan-ipv6
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alpine-ipvlan-ipv6
  template:
    metadata:
      labels:
        app: alpine-ipvlan-ipv6
      annotations:
        flatnetwork.pandaria.io/ip: "auto"
        flatnetwork.pandaria.io/subnet: "ipvlan-ipv6-subnet201"
        flatnetwork.pandaria.io/mac: ""
        k8s.v1.cni.cncf.io/networks: '[{"name":"rancher-flat-network","interface":"eth1"}]'
    spec:
      containers:
      - name: alpine-ipvlan
        image: alpine
        command: ["sleep"]
        args: ["infinity"]
