kind: Pod
apiVersion: v1
metadata:
  name: example-ipvlan-pod
  namespace: "default"
  annotations:
    flatnetwork.pandaria.io/ip: "auto"
    flatnetwork.pandaria.io/subnet: "example-ipvlan-subnet"
    flatnetwork.pandaria.io/mac: ""
spec:
  containers:
  - name: alpine
    image: alpine
    command:
    - "sleep"
    args:
    - "infinity"
