apiVersion: v1
kind: Service
metadata:
  name: example-ipvlan-service
spec:
  type: NodePort
  selector:
    app: nginx-ipvlan
  ports:
    - port: 80
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: example-ipvlan-service-ipv6
spec:
  type: NodePort
  selector:
    app: nginx-ipvlan-ipv6
  ports:
    - port: 80
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 80
