apiVersion: flatnetwork.pandaria.io/v1
kind: FlatNetworkSubnet
metadata:
  labels:
    project: ""
  name: example-ipvlan-subnet
  namespace: kube-system
spec:
  vlan: 0
  cidr: 192.168.2.0/24
  flatMode: ipvlan
  gateway: ""
  master: eth0
  mode: "l2"
  podDefaultGateway: {}
  ranges:
  - end: 192.168.2.150
    from: 192.168.2.100
