apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: flatnetwork-subnets-validating-config
  labels:
    app: flatnetwork-operator
webhooks:
  - name: flatnetwork-subnets-validating-config.kube-system.svc.cluster.local
    failurePolicy: Ignore
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    timeoutSeconds: 5
    clientConfig:
      service:
        name: flatnetwork-operator-webhook-svc
        namespace: kube-system
        path: "/validate"
      caBundle: ${CA_BUNDLE}
    rules:
      - operations: [ "CREATE", "UPDATE" ]
        apiGroups: [ "flatnetwork.pandaria.io" ]
        apiVersions: [ "v1" ]
        resources: [ "flatnetworksubnets" ]
      - operations: [ "CREATE", "UPDATE" ]
        apiGroups: [ "apps" ]
        apiVersions: [ "v1" ]
        resources: [ "deployments", "daemonsets", "statefulsets" ]
      - operations: [ "CREATE", "UPDATE" ]
        apiGroups: [ "batch" ]
        apiVersions: [ "v1", "v1beta1" ]
        resources: [ "cronjobs", "jobs" ]
