apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment
  namespace: default
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        macvlan.pandaria.cattle.io/ip: "auto"
        macvlan.pandaria.cattle.io/subnet: "example-subnet"
        macvlan.pandaria.cattle.io/mac: ""
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
