apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment
  namespace: default
  labels:
    app: alpine
spec:
  replicas: 5
  selector:
    matchLabels:
      app: alpine
  template:
    metadata:
      labels:
        app: alpine
      annotations:
        macvlan.pandaria.cattle.io/ip: "auto"
        macvlan.pandaria.cattle.io/subnet: "example-subnet"
        macvlan.pandaria.cattle.io/mac: ""
    spec:
      containers:
      - name: alpine
        image: alpine
        command:
        - "sleep"
        args:
        - "infinity"
