kind: Pod
apiVersion: v1
metadata:
  name: example-pod
  namespace: "default"
  annotations:
    macvlan.pandaria.cattle.io/ip: "auto"
    macvlan.pandaria.cattle.io/subnet: "example-subnet"
    macvlan.pandaria.cattle.io/mac: ""
spec:
  containers:
  - name: alpine
    image: alpine
    command:
    - "sleep"
    args:
    - "infinity"
