---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/resource-policy: keep
  name: macvlanips.macvlan.cluster.cattle.io
spec:
  group: macvlan.cluster.cattle.io
  names:
    kind: MacvlanIP
    plural: macvlanips
    shortNames:
    - mip
    - mips
    singular: macvlanip
  preserveUnknownFields: false
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              cidr:
                nullable: true
                type: string
              mac:
                nullable: true
                type: string
              podId:
                nullable: true
                type: string
              subnet:
                nullable: true
                type: string
            type: object
          status:
            properties:
              failureMessage:
                nullable: true
                type: string
              phase:
                nullable: true
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/resource-policy: keep
  name: macvlansubnets.macvlan.cluster.cattle.io
spec:
  group: macvlan.cluster.cattle.io
  names:
    kind: MacvlanSubnet
    plural: macvlansubnets
    shortNames:
    - msubnet
    - msubnets
    singular: macvlansubnet
  preserveUnknownFields: false
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              cidr:
                nullable: true
                type: string
              gateway:
                nullable: true
                type: string
              ipDelayReuse:
                type: integer
              master:
                nullable: true
                type: string
              mode:
                nullable: true
                type: string
              podDefaultGateway:
                properties:
                  enable:
                    type: boolean
                  serviceCidr:
                    nullable: true
                    type: string
                type: object
              ranges:
                items:
                  properties:
                    rangeEnd:
                      nullable: true
                      type: string
                    rangeStart:
                      nullable: true
                      type: string
                  type: object
                nullable: true
                type: array
              routes:
                items:
                  properties:
                    dst:
                      nullable: true
                      type: string
                    gw:
                      nullable: true
                      type: string
                    iface:
                      nullable: true
                      type: string
                  type: object
                nullable: true
                type: array
              vlan:
                type: integer
            type: object
          status:
            properties:
              allocatedIPs:
                items:
                  properties:
                    rangeEnd:
                      nullable: true
                      type: string
                    rangeStart:
                      nullable: true
                      type: string
                  type: object
                nullable: true
                type: array
              failureMessage:
                nullable: true
                type: string
              phase:
                nullable: true
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
